### ISSUE TITLE
配置 POST 请求/RESTFul 风格 API 的示例

### ISSUE THREAD

**Issue by leohxj** [funkyLover/mock-server#16]
第一个问题：
关于 POST 的方式，文档没有看到相关说明，我试了 POST 对应的请求，结果是 404.

响应为：`ENOENT: no such file or directory, stat .....`

第二个问题：
#7 应用是支持了 Restful 风格的接口配置，希望补充下使用说明。

**Comment by funkyLover** [comment]
关于第一条问题, 其实不需要针对get/post方法做处理,  是个bug刚刚已经修复, 可以更新在至`2.5.0`版本试试

关于第二条问题, 可按以下方式配置mock目录，启动后续会更新到文档中去

```js
// restful风格api: api.target.com/users/:id
// 启动且在mock面板勾选后，请求如 api.target.com/users/userid 即可
|- mock
  |- api.target.com
    |- users
      |- :id
        |- 返回用户信息
          |- data.js

// mock/api.target.com/users/:id/返回用户信息/data.js
module.exports = (ctx) => {
  return {
    data: {
      id: ctx.params.id
    }
  }
};
```

**Comment by leohxj** [comment]
不客气。
正好在选一个本地 mock 的方案，挺好的。

再问一个小问题，添加的 mock 默认是关闭的，需要进入 `http://localhost:8888/view` 然后点击开启。有没有默认启动的选项？

**Comment by funkyLover** [comment]
@leohxj 这里不做默认开启（如果接口只有一个mock选项）是考虑到在迭代过程中，并不是所有的api都需要mock的

当想一部分api进行mock，一部分api直接请求服务器时，可以这样配置代理工具（webpack.devServer也是类似的）

```bash
api.target.com 127.0.0.1:8888
```

只需要把所有的接口直接都转发到mock server即可，如果对应api没有勾选任一mock选项或根本没有针对该api进行配置时，mock server会直接把请求转发到域名对应的目标服务器

更进一步，可以通过[proxy.js](https://github.com/funkyLover/mock-server/blob/dev/docs/zh/proxy.md)指定不同的host转发规则

而如果默认开启的话（假设一个api下只有一个mock选项时默认开启），想做到一部分api进行mock，一部分api直接请求服务器时，则需要按下面的方式去配置代理工具

```bash
api.target.com/api/login www.xxx.yyy.zzz
api.target.com/api/users www.xxx.yyy.zzz
api.target.com 127.0.0.1:8888
```

因为这个工具一开始诞生于团队的需求，团队成员一致认为前者的用法更方便，所以才没有做默认启动

不过有些场景下的确默认启动也是也能减少操作成本，不知道有没有什么建议呢？在保留上述特性的同时，增加默认启动（例如mock文件名有特殊前缀？）

**Comment by leohxj** [comment]
理解，这个做法很贴近实际业务，工具首先服务好团队。

我作为一个使用者，喜欢的方式是这样：
- 启动的 mock 服务还是 `http://localhost:8888`，展示 mock 数据的列表，并可通过 `http://localhost:8888/user/:id` 方式访问对应 mock 数据， 类似 `json-server`
- 管理台可另起端口或命令约定式访问，比如`http://localhost:8888/_admin`
- mock 数据默认开启 data.js 文件
- 配置开发环境的 Proxy 将接口转发到 mock 服务中:
```js
{
    '/api': {
        target: 'http://127.0.0.1:8888/',
        changeOrigin: true,
        pathRewrite: { '^/api': '/' },
    },
}
```
- mock 工具自身可带配置文件，配置：
	- 哪些请求需要做 fallback 转发, 默认关闭，个人觉得特性功能尽量少的默认开启。
```js
{
  port: 8888,
  proxy: {
    '/api/login' : {
      host: 'www.xxxx.yyy.zzz'
    }
  }
}
```

既然使用 mock 工具，我感觉还是希望默认是 mock 状态。然后再给予当 mock 数据未录入/未开启时的转发功能。

个人愚见。


再请教个问题。接口的变更你们如何做同步，这类工具使用过程中我感觉最麻烦的就是后续的接口更新，如何保持和接口的定义的一致性问题。

**Comment by funkyLover** [comment]
感谢你的建议，其中有蛮不错值得mock-server思考改进的地方

关于第一点要提一下，为什么当前mock-server不支持通过本地ip`http://localhost:8888/user/:id`的方式直接请求到对应的mock数据

是因为mock-server本来的场景是考虑到一个项目有多个业务域名的情况

```
# 如果mock目录配置如下
|- mock
  |- api.target.com
    |- users/:id
  |- api.mock.com
    |- users/:id
```

这个使用直接访问`http://localhost:8888/user/:id`就不好判断应该命中哪一个mock了，所以在实现的时候采用了匹配host的做法，所以在对业务请求转发时才需要对host进行重写

```
proxyTable: {
  '/users': {
    target: 'http://127.0.0.1:8888',
    headers: {
      host: 'api.target.com' // 重写host
    }
  }
}
```

关于最后的问题可以交流一下，如果需求是要做接口管理（而不是简单的mock）的话，例如像打通后端，测试等等，大家通过云端方式管理接口的话，业界中[easy-mock](https://github.com/easy-mock/easy-mock)、[yapi](https://github.com/YMFE/yapi)这种解决方案会更加合适。

而mock-server这个工具本身就只是为了mock而已，在多人协作时，也只是推荐把mock数据存放在项目仓库之中，通过git进行管理，保证大家的mock数据在当前版本迭代中相对一致而已。

**Comment by leohxj** [comment]
恩。有想法再交流 :)
